import { WorldViewManager } from "../wsManager";

export const CURATED_WEBCAMS = [
  {
    id: "times-square",
    name: "Times Square",
    park: "Midtown Manhattan",
    region: "North America",
    type: "snapshot",
    latitude: 40.758,
    longitude: -73.9855,
    viewerUrl: "https://www.earthcam.com/usa/newyork/timessquare/?cam=tsrobo1",
    externalUrl: "https://www.earthcam.com/usa/newyork/timessquare/",
    embedUrl: "",
    snapshotUrl: "https://images.earthcam.com/ec_metros/ourcams/fridays.jpg",
    refreshSeconds: 60,
    source: "EarthCam",
    availability: "Public",
    description: "Live view of Times Square, New York City.",
  },
  {
    id: "eiffel-tower",
    name: "Eiffel Tower",
    park: "Paris",
    region: "Europe",
    type: "snapshot",
    latitude: 48.8584,
    longitude: 2.2945,
    viewerUrl: "https://www.earthcam.com/world/france/paris/?cam=eiffel_tower",
    externalUrl: "https://www.earthcam.com/world/france/paris/",
    embedUrl: "",
    snapshotUrl: "https://images.earthcam.com/ec_metros/ourcams/eiffel.jpg",
    refreshSeconds: 60,
    source: "EarthCam",
    availability: "Public",
    description: "Live view of the Eiffel Tower, Paris.",
  },
  {
    id: "tokyo-shibuya",
    name: "Shibuya Crossing",
    park: "Tokyo",
    region: "Asia Pacific",
    type: "snapshot",
    latitude: 35.6595,
    longitude: 139.7004,
    viewerUrl: "https://www.earthcam.com/world/japan/tokyo/?cam=shibuya",
    externalUrl: "https://www.earthcam.com/world/japan/tokyo/",
    embedUrl: "",
    snapshotUrl: "https://images.earthcam.com/ec_metros/ourcams/shibuya.jpg",
    refreshSeconds: 60,
    source: "EarthCam",
    availability: "Public",
    description: "Live view of Shibuya Crossing, Tokyo.",
  },
  {
    id: "sydney-opera",
    name: "Sydney Opera House",
    park: "Sydney Harbour",
    region: "Asia Pacific",
    type: "snapshot",
    latitude: -33.8568,
    longitude: 151.2153,
    viewerUrl: "https://www.earthcam.com/world/australia/sydney/?cam=sydneyoperahouse",
    externalUrl: "https://www.earthcam.com/world/australia/sydney/",
    embedUrl: "",
    snapshotUrl: "https://images.earthcam.com/ec_metros/ourcams/sydney.jpg",
    refreshSeconds: 60,
    source: "EarthCam",
    availability: "Public",
    description: "Live view of Sydney Opera House.",
  },
  {
    id: "london-tower",
    name: "Tower Bridge",
    park: "London",
    region: "Europe",
    type: "snapshot",
    latitude: 51.5055,
    longitude: -0.0754,
    viewerUrl: "https://www.earthcam.com/world/england/london/?cam=towerbridgee",
    externalUrl: "https://www.earthcam.com/world/england/london/",
    embedUrl: "",
    snapshotUrl: "https://images.earthcam.com/ec_metros/ourcams/londonbridge.jpg",
    refreshSeconds: 60,
    source: "EarthCam",
    availability: "Public",
    description: "Live view of Tower Bridge, London.",
  },
  {
    id: "niagara-falls",
    name: "Niagara Falls",
    park: "Niagara Falls State Park",
    region: "North America",
    type: "snapshot",
    latitude: 43.0799,
    longitude: -79.0747,
    viewerUrl: "https://www.earthcam.com/usa/newyork/niagarafalls/?cam=niagarafalls_horseshoe",
    externalUrl: "https://www.earthcam.com/usa/newyork/niagarafalls/",
    embedUrl: "",
    snapshotUrl: "https://images.earthcam.com/ec_metros/ourcams/niagara.jpg",
    refreshSeconds: 60,
    source: "EarthCam",
    availability: "Public",
    description: "Live view of Niagara Falls.",
  },
  {
    id: "dubai-burj",
    name: "Burj Khalifa",
    park: "Downtown Dubai",
    region: "Middle East",
    type: "snapshot",
    latitude: 25.1972,
    longitude: 55.2744,
    viewerUrl: "https://www.earthcam.com/world/uae/dubai/?cam=burjkhalifa",
    externalUrl: "https://www.earthcam.com/world/uae/dubai/",
    embedUrl: "",
    snapshotUrl: "https://images.earthcam.com/ec_metros/ourcams/dubai.jpg",
    refreshSeconds: 60,
    source: "EarthCam",
    availability: "Public",
    description: "Live view of Burj Khalifa, Dubai.",
  },
  {
    id: "rio-christ",
    name: "Christ the Redeemer",
    park: "Rio de Janeiro",
    region: "South America",
    type: "snapshot",
    latitude: -22.9519,
    longitude: -43.2105,
    viewerUrl: "https://www.earthcam.com/world/brazil/riodejaneiro/?cam=rio",
    externalUrl: "https://www.earthcam.com/world/brazil/riodejaneiro/",
    embedUrl: "",
    snapshotUrl: "https://images.earthcam.com/ec_metros/ourcams/rio.jpg",
    refreshSeconds: 60,
    source: "EarthCam",
    availability: "Public",
    description: "Live view of Christ the Redeemer, Rio de Janeiro.",
  },
];

export async function startWebcamWorker(manager: WorldViewManager): Promise<void> {
  const webcams = CURATED_WEBCAMS.map(cam => ({
    ...cam,
    proxySnapshotUrl: `/api/webcams/${cam.id}/snapshot`,
  }));

  manager.broadcast("webcams", webcams);
  manager.updateFeedStatus("webcams", {
    status: "live",
    detail: `${webcams.length} curated public webcams ready`,
    itemCount: webcams.length,
  });
}
